---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
      docker:
        patterns:
          - "docker/*"
      artifact:
        patterns:
          - "actions/*-artifact"
