name: Bug Report
description: Create a bug report to help us improve ParquetSharp
title: "[BUG]: <title>"
labels: [ "Bug" ]

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for reporting this issue!**        
        To help us understand and address the problem effectively, please provide detailed information. 
        You can refer to [this guide](https://stackoverflow.com/help/mcve) for tips on creating a good bug report.

  - type: textarea
    id: describe-issue
    attributes:
      label: Issue Description
      description: A clear and concise description of the issue
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: "Please provide the following details:"
      value: |
        - ParquetSharp Version:  [e.g. 1.0.1]
        - .NET Framework/SDK Version: [e.g. .NET Framework 4.7.2]
        - Operating System: [e.g. Windows 10]
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Provide a minimal code example or steps.
        2. Explain the exact error message or current behavior.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context (Optional)
      description: Add any other context about the problem here, including log outputs or screenshots if applicable.
    validations:
      required: false
